import { StyleSheet } from "react-native";
import colors from "../../constants/colors";
import fonts from "../../constants/fonts";
import { fontScale, moderateScale, verticalScale } from "../../constants/metrics";

const base = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.background },
  container: { flex: 1 },
  header: {
    minHeight: verticalScale(58),
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: moderateScale(8),
    borderBottomWidth: 1,
    borderBottomColor: colors.cardBorder,
    backgroundColor: colors.white,
  },
  headerCopy: { flex: 1, minWidth: 0 },
  headerTitle: { fontSize: fontScale(16), fontFamily: fonts.bold, color: colors.textDark },
  headerSubtitle: { marginTop: verticalScale(1), fontSize: fontScale(9.5), fontFamily: fonts.medium, color: colors.textSecondary, textTransform: "uppercase", letterSpacing: 0.7 },
  headerMaterialBadge: { minWidth: moderateScale(43), alignItems: "center", paddingHorizontal: moderateScale(10), paddingVertical: verticalScale(6), borderRadius: moderateScale(999), backgroundColor: colors.surfaceBlue, borderWidth: 1, borderColor: colors.cardBorder },
  headerMaterialText: { fontSize: fontScale(11), fontFamily: fonts.bold, color: colors.primaryBlue },
  scroll: { flex: 1 },
  scrollContent: { padding: moderateScale(14), paddingBottom: verticalScale(24), gap: verticalScale(12) },
  heroCard: { position: "relative", overflow: "hidden", flexDirection: "row", alignItems: "center", padding: moderateScale(14), paddingBottom: verticalScale(19), borderRadius: moderateScale(18), borderCurve: "continuous", backgroundColor: colors.primaryBlue, boxShadow: "0 5px 16px rgba(18,59,99,0.18)" },
  heroCopy: { flex: 1, minWidth: 0 },
  heroEyebrow: { fontSize: fontScale(9), fontFamily: fonts.bold, color: "#BBD7EE", letterSpacing: 1 },
  heroTitle: { marginTop: verticalScale(3), fontSize: fontScale(18), fontFamily: fonts.bold, color: colors.white },
  heroMeta: { marginTop: verticalScale(3), fontSize: fontScale(10), fontFamily: fonts.medium, color: "#D8E8F5" },
  progressRing: { width: moderateScale(52), height: moderateScale(52), alignItems: "center", justifyContent: "center", borderRadius: moderateScale(26), borderWidth: 4, borderColor: "rgba(255,255,255,0.28)", backgroundColor: "rgba(255,255,255,0.08)" },
  progressRingValue: { fontSize: fontScale(13), fontFamily: fonts.bold, color: colors.white, fontVariant: ["tabular-nums"] },
  progressTrack: { position: "absolute", left: moderateScale(14), right: moderateScale(14), bottom: verticalScale(8), height: verticalScale(4), borderRadius: moderateScale(999), overflow: "hidden", backgroundColor: "rgba(255,255,255,0.18)" },
  progressFill: { height: "100%", borderRadius: moderateScale(999), backgroundColor: "#63D5A4" },
  sectionCard: { padding: moderateScale(13), borderRadius: moderateScale(18), borderCurve: "continuous", borderWidth: 1, borderColor: colors.cardBorder, backgroundColor: colors.white, boxShadow: "0 3px 12px rgba(18,59,99,0.06)" },
  sectionHeadingRow: { flexDirection: "row", alignItems: "center", gap: moderateScale(9), paddingBottom: verticalScale(10) },
  sectionIcon: { width: moderateScale(36), height: moderateScale(36), alignItems: "center", justifyContent: "center", borderRadius: moderateScale(11), backgroundColor: colors.surfaceBlue },
  sectionHeadingCopy: { flex: 1 },
  sectionTitle: { fontSize: fontScale(15), fontFamily: fonts.bold, color: colors.textDark },
  sectionSubtitle: { marginTop: verticalScale(1), fontSize: fontScale(9.5), fontFamily: fonts.regular, color: colors.textSecondary },
  twoColumnRow: { flexDirection: "row", alignItems: "flex-end", gap: moderateScale(8) },
  column: { flex: 0.85, minWidth: 0 },
  wideColumn: { flex: 1.65 },
  fieldBlock: { minWidth: 0 },
  fieldLabel: { marginBottom: verticalScale(5), fontSize: fontScale(9.5), fontFamily: fonts.bold, color: colors.textSecondary, letterSpacing: 0.35 },
  required: { color: colors.danger },
  selectField: { minHeight: verticalScale(44), flexDirection: "row", alignItems: "center", gap: moderateScale(5), paddingHorizontal: moderateScale(11), borderRadius: moderateScale(11), borderCurve: "continuous", borderWidth: 1, borderColor: colors.border, backgroundColor: colors.inputBg },
  selectText: { flex: 1, fontSize: fontScale(11.5), fontFamily: fonts.medium, color: colors.textDark },
  placeholder: { color: "#8CA0B5" },
  fieldError: { borderColor: colors.danger, backgroundColor: "#FFF8F8" },
  fieldPressed: { opacity: 0.72 },
  datePickerCard: { marginTop: verticalScale(8), overflow: "hidden", borderRadius: moderateScale(14), borderWidth: 1, borderColor: colors.cardBorder, backgroundColor: colors.surfaceBluePale },
  dateDoneButton: { alignSelf: "flex-end", paddingHorizontal: moderateScale(16), paddingVertical: verticalScale(8) },
  dateDoneText: { fontSize: fontScale(12), fontFamily: fonts.bold, color: colors.primaryBlue },
  pipeInfoGrid: { marginTop: verticalScale(10), flexDirection: "row", flexWrap: "wrap", overflow: "hidden", borderRadius: moderateScale(12), borderWidth: 1, borderColor: colors.cardBorder, backgroundColor: colors.surfaceBluePale },
  pipeInfoItem: { width: "33.333%", minHeight: verticalScale(49), justifyContent: "center", paddingHorizontal: moderateScale(9), paddingVertical: verticalScale(7), borderRightWidth: 1, borderBottomWidth: 1, borderColor: colors.cardBorder },
  pipeInfoLabel: { fontSize: fontScale(8), fontFamily: fonts.bold, color: colors.textSecondary, textTransform: "uppercase", letterSpacing: 0.45 },
  pipeInfoValue: { marginTop: verticalScale(2), fontSize: fontScale(10.5), fontFamily: fonts.bold, color: colors.textDark },
  formGrid: { marginTop: verticalScale(10), marginBottom: verticalScale(10), flexDirection: "row", flexWrap: "wrap", gap: moderateScale(8) },
  formHalf: { width: "48.6%" },
  formFull: { width: "100%" },
  formThird: { flex: 1, minWidth: moderateScale(78) },
  textField: { minHeight: verticalScale(44), paddingHorizontal: moderateScale(11), paddingVertical: verticalScale(9), borderRadius: moderateScale(11), borderCurve: "continuous", borderWidth: 1, borderColor: colors.border, backgroundColor: colors.inputBg, fontSize: fontScale(11.5), fontFamily: fonts.medium, color: colors.textDark },
  remarkField: { minHeight: verticalScale(68), marginBottom: 0 },
  stageTabs: { gap: moderateScale(7), paddingBottom: verticalScale(10) },
  stageTab: { minHeight: verticalScale(36), justifyContent: "center", paddingHorizontal: moderateScale(14), borderRadius: moderateScale(999), borderWidth: 1, borderColor: colors.cardBorder, backgroundColor: colors.surfaceBluePale },
  stageTabText: { fontSize: fontScale(10), fontFamily: fonts.bold, color: colors.textSecondary },
  stageTabTextActive: { color: colors.white },
  checklistHeading: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: moderateScale(2) },
  checklistEyebrow: { fontSize: fontScale(10), fontFamily: fonts.bold, color: colors.primaryBlue, letterSpacing: 0.65 },
  checklistTitle: { marginTop: verticalScale(2), fontSize: fontScale(13), fontFamily: fonts.bold, color: colors.textDark },
  completedBadge: { minWidth: moderateScale(50), alignItems: "center", paddingHorizontal: moderateScale(10), paddingVertical: verticalScale(6), borderRadius: moderateScale(999), backgroundColor: colors.lightGreen },
  completedBadgeText: { fontSize: fontScale(10.5), fontFamily: fonts.bold, color: colors.primaryGreen, fontVariant: ["tabular-nums"] },
  checklistSection: { overflow: "hidden", borderRadius: moderateScale(16), borderCurve: "continuous", borderWidth: 1, borderColor: colors.cardBorder, backgroundColor: colors.white },
  checklistSectionHeader: { minHeight: verticalScale(40), flexDirection: "row", alignItems: "center", paddingHorizontal: moderateScale(12), gap: moderateScale(8) },
  sectionMarker: { width: moderateScale(4), height: verticalScale(21), borderRadius: moderateScale(999) },
  checklistSectionTitle: { flex: 1, fontSize: fontScale(12), fontFamily: fonts.bold, textTransform: "uppercase", letterSpacing: 0.5 },
  checklistSectionCount: { fontSize: fontScale(9), fontFamily: fonts.bold },
  checklistRow: { flexDirection: "row", alignItems: "flex-start", gap: moderateScale(9), paddingHorizontal: moderateScale(11), paddingVertical: verticalScale(9), borderBottomWidth: 1, borderBottomColor: "#E8F0F7" },
  checklistRowToggle: { alignItems: "center" },
  checklistRowLast: { borderBottomWidth: 0 },
  checkNumber: { width: moderateScale(24), height: moderateScale(24), alignItems: "center", justifyContent: "center", borderRadius: moderateScale(8) },
  checkNumberText: { fontSize: fontScale(9.5), fontFamily: fonts.bold, fontVariant: ["tabular-nums"] },
  checkCopy: { flex: 1, minWidth: 0 },
  checkTitle: { fontSize: fontScale(12), lineHeight: fontScale(16), fontFamily: fonts.bold, color: colors.textDark },
  checkDescription: { marginTop: verticalScale(2), fontSize: fontScale(9.5), lineHeight: fontScale(14), fontFamily: fonts.regular, color: colors.textSecondary },
  checkDescriptionPrimary: { flex: 1, fontSize: fontScale(10.5), lineHeight: fontScale(15), fontFamily: fonts.medium, color: colors.textDark },
  responseWrap: { marginTop: verticalScale(7), alignItems: "flex-start" },
  checkToggle: { width: moderateScale(36), minHeight: verticalScale(36), alignItems: "center", justifyContent: "center", flexShrink: 0 },
  okControl: { minHeight: verticalScale(34), flexDirection: "row", alignItems: "center", gap: moderateScale(7), paddingHorizontal: moderateScale(10), borderRadius: moderateScale(10), borderWidth: 1, borderColor: colors.cardBorder, backgroundColor: colors.surfaceBluePale },
  okControlActive: { borderColor: "#9AD6B8", backgroundColor: colors.lightGreen },
  checkbox: { width: moderateScale(19), height: moderateScale(19), alignItems: "center", justifyContent: "center", borderRadius: moderateScale(6), borderWidth: 1.5, borderColor: "#9CB0C3", backgroundColor: colors.white },
  checkboxActive: { borderColor: colors.primaryGreen, backgroundColor: colors.primaryGreen },
  okText: { fontSize: fontScale(10.5), fontFamily: fonts.bold, color: colors.textSecondary },
  okTextActive: { color: colors.primaryGreen },
  inlineSelect: { width: "100%", minHeight: verticalScale(40), flexDirection: "row", alignItems: "center", paddingHorizontal: moderateScale(10), borderRadius: moderateScale(10), borderWidth: 1, borderColor: colors.border, backgroundColor: colors.inputBg },
  inlineSelectText: { flex: 1, fontSize: fontScale(10.5), fontFamily: fonts.medium, color: colors.textDark },
  inlineInput: { width: "100%", minHeight: verticalScale(40), paddingHorizontal: moderateScale(10), borderRadius: moderateScale(10), borderWidth: 1, borderColor: colors.border, backgroundColor: colors.inputBg, fontSize: fontScale(10.5), fontFamily: fonts.medium, color: colors.textDark },
  photoButton: { minHeight: verticalScale(38), flexDirection: "row", alignItems: "center", gap: moderateScale(7), paddingHorizontal: moderateScale(11), borderRadius: moderateScale(10), borderWidth: 1, borderColor: "#C9D9EA", backgroundColor: colors.surfaceBluePale },
  photoButtonAdded: { borderColor: "#9AD6B8", backgroundColor: colors.lightGreen },
  photoThumbnail: { width: moderateScale(25), height: moderateScale(25), borderRadius: moderateScale(7) },
  photoButtonText: { fontSize: fontScale(10.5), fontFamily: fonts.bold, color: colors.primaryBlue },
  photoButtonTextAdded: { color: colors.primaryGreen },
  footer: { flexDirection: "row", alignItems: "center", gap: moderateScale(9), paddingTop: verticalScale(10), paddingHorizontal: moderateScale(14), borderTopWidth: 1, borderTopColor: colors.cardBorder, backgroundColor: colors.white, boxShadow: "0 -4px 14px rgba(18,59,99,0.08)" },
  cancelButton: { minHeight: verticalScale(46), alignItems: "center", justifyContent: "center", paddingHorizontal: moderateScale(18), borderRadius: moderateScale(13), borderWidth: 1, borderColor: colors.cardBorder, backgroundColor: colors.white },
  cancelButtonText: { fontSize: fontScale(12), fontFamily: fonts.bold, color: colors.textSecondary },
  saveButton: { flex: 1, minHeight: verticalScale(46), flexDirection: "row", alignItems: "center", justifyContent: "center", gap: moderateScale(7), borderRadius: moderateScale(13), backgroundColor: colors.primaryBlue, boxShadow: "0 4px 12px rgba(18,59,99,0.2)" },
  saveButtonText: { fontSize: fontScale(13), fontFamily: fonts.bold, color: colors.white },
  buttonDisabled: { opacity: 0.58 },
  buttonPressed: { opacity: 0.78, transform: [{ scale: 0.99 }] },
});

// Keep the app palette and typefaces, with device-independent form touch targets.
export default StyleSheet.create({
  ...base,
  scrollContent: { padding: 16, paddingBottom: 28, gap: 16, width: "100%", maxWidth: 720, alignSelf: "center" },
  headerTitle: { ...base.headerTitle, fontSize: 20 },
  headerSubtitle: { ...base.headerSubtitle, fontSize: 12, textTransform: "none", letterSpacing: 0 },
  sectionCard: { padding: 16, borderRadius: 20, backgroundColor: colors.white, gap: 4 },
  sectionHeadingRow: { ...base.sectionHeadingRow, paddingBottom: 16 },
  sectionTitle: { ...base.sectionTitle, fontSize: 18 },
  sectionSubtitle: { ...base.sectionSubtitle, fontSize: 12, marginTop: 4 },
  twoColumnRow: { gap: 16 },
  column: { width: "100%" },
  wideColumn: {},
  fieldLabel: { ...base.fieldLabel, fontSize: 13, marginBottom: 8, letterSpacing: 0 },
  selectField: { ...base.selectField, minHeight: 52, paddingVertical: 12, paddingHorizontal: 14, borderRadius: 12, backgroundColor: colors.white },
  selectText: { ...base.selectText, fontSize: 15 },
  textField: { ...base.textField, minHeight: 52, fontSize: 16, paddingHorizontal: 14, paddingVertical: 12, borderRadius: 12, backgroundColor: colors.white },
  fieldFocused: { borderColor: colors.primaryBlue, borderWidth: 1.5, backgroundColor: colors.surfaceBluePale },
  errorText: { fontSize: 12, color: colors.danger, marginTop: 6 },
  formGrid: { ...base.formGrid, gap: 12, marginVertical: 18 },
  formHalf: { flexGrow: 1, flexBasis: "45%", minWidth: 0 },
  formFull: { width: "100%", flexBasis: "100%" },
  formThird: { flexGrow: 1, flexBasis: "28%", minWidth: 0 },
  pipeInfoGrid: { ...base.pipeInfoGrid, marginTop: 16, borderWidth: 0, padding: 4 },
  pipeInfoItem: { ...base.pipeInfoItem, borderWidth: 0, borderBottomWidth: 0, borderRightWidth: 0, padding: 10, minHeight: 60 },
  pipeInfoLabel: { ...base.pipeInfoLabel, fontSize: 11, textTransform: "none", letterSpacing: 0 },
  pipeInfoValue: { ...base.pipeInfoValue, fontSize: 13, marginTop: 4 },
  stageTab: { ...base.stageTab, minHeight: 48, borderRadius: 12 },
  stageTabText: { ...base.stageTabText, fontSize: 13 },
  remarkField: { minHeight: 96 },
  heroCard: { ...base.heroCard, borderRadius: 16, padding: 16, paddingBottom: 24, boxShadow: "none" },
  heroTitle: { ...base.heroTitle, fontSize: 18 },
  heroMeta: { ...base.heroMeta, fontSize: 13 },
  checklistTitle: { ...base.checklistTitle, fontSize: 17 },
  checklistSectionHeader: { ...base.checklistSectionHeader, minHeight: 56, paddingVertical: 12 },
  checklistSectionTitle: { ...base.checklistSectionTitle, fontSize: 15, textTransform: "none", letterSpacing: 0 },
  checklistSectionCount: { ...base.checklistSectionCount, fontSize: 12 },
  checklistRow: { ...base.checklistRow, paddingHorizontal: 14, paddingVertical: 11, gap: 10 },
  checklistRowToggle: { ...base.checklistRowToggle },
  checkTitle: { ...base.checkTitle, fontSize: 15, lineHeight: 21 },
  checkDescription: { ...base.checkDescription, fontSize: 13, lineHeight: 19, marginTop: 6 },
  checkDescriptionPrimary: { ...base.checkDescriptionPrimary, fontSize: 14, lineHeight: 20 },
  responseWrap: { marginTop: 9, alignItems: "stretch" },
  checkToggle: { ...base.checkToggle, width: 40, minHeight: 40 },
  okControl: { ...base.okControl, minHeight: 48, paddingVertical: 10, borderRadius: 12 },
  okText: { ...base.okText, fontSize: 14 },
  inlineInput: { ...base.inlineInput, minHeight: 52, fontSize: 15, paddingVertical: 12 },
  inlineSelect: { ...base.inlineSelect, minHeight: 52, paddingVertical: 12 },
  inlineSelectText: { ...base.inlineSelectText, fontSize: 14 },
  photoButton: { ...base.photoButton, minHeight: 52, paddingVertical: 10, borderStyle: "dashed" },
  photoButtonText: { ...base.photoButtonText, fontSize: 14 },
  photoThumbnail: { width: 44, height: 44, borderRadius: 8 },
  photoPreviewRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  footer: { ...base.footer, paddingHorizontal: 16, paddingTop: 12, boxShadow: "none" },
  saveButton: { ...base.saveButton, minHeight: 52, paddingVertical: 12, paddingHorizontal: 12 },
  saveButtonText: { ...base.saveButtonText, fontSize: 15, flexShrink: 1, textAlign: "center" },
  cancelButton: { ...base.cancelButton, minHeight: 52 },
  cancelButtonText: { ...base.cancelButtonText, fontSize: 14 },
  processSelector: { paddingHorizontal: 16, paddingVertical: 12, gap: 10, backgroundColor: colors.white, borderBottomWidth: 1, borderBottomColor: colors.cardBorder },
  processSelectorHeading: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: 6 },
  processHeadingMeta: { flexDirection: "row", alignItems: "center", gap: 8 },
  processCounter: { fontSize: 12, fontFamily: fonts.medium, color: colors.textSecondary },
  networkBadge: { minHeight: 24, flexDirection: "row", alignItems: "center", gap: 4, paddingHorizontal: 7, borderRadius: 12, borderWidth: 1, borderColor: "#F1D29A", backgroundColor: "#FFF7E8" },
  networkBadgeHidden: { opacity: 0 },
  networkBadgeText: { fontSize: 10, fontFamily: fonts.bold, color: colors.pending },
  processOptions: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  processOption: { flexGrow: 1, flexBasis: "20%", minWidth: 65, minHeight: 44, paddingHorizontal: 6, paddingVertical: 10, borderRadius: 10, borderWidth: 1, borderColor: colors.cardBorder, backgroundColor: colors.surfaceBluePale, alignItems: "center", justifyContent: "center" },
  processOptionActive: { borderColor: colors.primaryBlue, backgroundColor: colors.primaryBlue },
  processOptionText: { fontSize: 12, fontFamily: fonts.bold, color: colors.textSecondary, textAlign: "center" },
  processHint: { fontSize: 12, lineHeight: 17, fontFamily: fonts.regular, color: colors.textSecondary },
  syncBanner: { flexDirection: "row", alignItems: "center", gap: 10, padding: 12, borderRadius: 14, borderWidth: 1, borderColor: colors.cardBorder, backgroundColor: colors.surfaceBlue },
  syncBannerOffline: { backgroundColor: "#FFF7E8", borderColor: "#F1D29A" },
  syncBannerIcon: { width: 36, height: 36, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: colors.white },
  syncBannerCopy: { flex: 1, minWidth: 0, gap: 2 },
  syncBannerTitle: { fontSize: 13, fontFamily: fonts.bold, color: colors.textDark },
  syncBannerText: { fontSize: 11, lineHeight: 16, fontFamily: fonts.regular, color: colors.textSecondary },
  loadNotice: { flexDirection: "row", alignItems: "center", gap: 8, padding: 11, borderRadius: 12, borderWidth: 1, borderColor: "#F1D29A", backgroundColor: "#FFF9EF" },
  loadNoticeText: { flex: 1, fontSize: 11, lineHeight: 15, fontFamily: fonts.regular, color: colors.textDark },
  retryButton: { minHeight: 34, paddingHorizontal: 11, borderRadius: 9, alignItems: "center", justifyContent: "center", backgroundColor: colors.white, borderWidth: 1, borderColor: colors.cardBorder },
  retryButtonText: { fontSize: 11, fontFamily: fonts.bold, color: colors.primaryBlue },
  skeletonCard: { padding: 16, gap: 14, borderRadius: 20, borderCurve: "continuous", borderWidth: 1, borderColor: colors.cardBorder, backgroundColor: colors.white, overflow: "hidden" },
  skeletonHeading: { flexDirection: "row", alignItems: "center", gap: 10 },
  skeletonHeadingCopy: { flex: 1, gap: 7 },
  skeletonFieldRow: { flexDirection: "row", gap: 12 },
  skeletonBlock: { overflow: "hidden", backgroundColor: "#E8F0F7", borderRadius: 10 },
  skeletonIcon: { width: 38, height: 38, borderRadius: 12 },
  skeletonTitle: { width: "48%", height: 16 },
  skeletonSubtitle: { width: "70%", height: 10 },
  skeletonField: { flex: 1, height: 54 },
  skeletonInfo: { width: "100%", height: 108 },
  skeletonChecklist: { width: "100%", height: 64 },
  skeletonSweep: { position: "absolute", top: 0, bottom: 0, left: -130, width: 104 },
  skeletonGradient: { flex: 1 },
  stepBar: { flexDirection: "row", padding: 12, gap: 8, backgroundColor: colors.white },
  stepButton: { flex: 1, minHeight: 48, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, padding: 10, borderRadius: 12 },
  stepActive: { backgroundColor: colors.surfaceBlue },
  stepText: { fontSize: 14, fontFamily: fonts.bold, color: colors.textSecondary, flexShrink: 1 },
  stepNumber: { fontSize: 13, fontFamily: fonts.bold, color: colors.textSecondary },
  stepActiveText: { color: colors.primaryBlue },
});
