import { StyleSheet } from "react-native";
import colors from "../../constants/colors";
import fonts from "../../constants/fonts";

export default StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.white },
  content: { padding: 12, gap: 8, width: "100%", maxWidth: 820, alignSelf: "center" },
  header: { gap: 8, marginBottom: 2 },
  top: { flexDirection: "row", alignItems: "center", gap: 12 },
  grow: { flex: 1, minWidth: 0 },
  eyebrow: { fontFamily: fonts.bold, color: colors.textSecondary, fontSize: 11, letterSpacing: 1 },
  project: { fontFamily: fonts.bold, fontSize: 17, color: colors.primaryBlue, marginTop: 4 },
  button: { minHeight: 44, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 10, backgroundColor: colors.primaryBlue, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6 },
  buttonText: { fontFamily: fonts.bold, color: colors.white, fontSize: 13 },
  filters: { gap: 8 },
  search: { flexDirection: "row", alignItems: "center", backgroundColor: colors.surfaceBlue, borderWidth: 1, borderColor: colors.cardBorder, borderRadius: 24, paddingHorizontal: 16, gap: 8, minHeight: 48, marginBottom: 4 },
  searchClear: { minWidth: 44, minHeight: 44, justifyContent: "center", alignItems: "center" },
  filterActive: { backgroundColor: colors.surfaceBlue, borderColor: colors.filterPanelBorder },
  pressed: { opacity: 0.65 },
  stage: { flexDirection: "row", alignItems: "center", gap: 6, flexShrink: 1 },
  stageDot: { width: 7, height: 7, borderRadius: 4 },
  stageChip: { alignSelf: "flex-start", borderRadius: 6, paddingHorizontal: 6, paddingVertical: 3 },
  stageText: { fontFamily: fonts.medium, fontSize: 12, color: colors.primaryBlue, flexShrink: 1 },
  input: { flex: 1, minWidth: 0, fontFamily: fonts.regular, fontSize: 14, color: colors.textDark, paddingVertical: 10 },
  row: { flexDirection: "row", gap: 8, flexWrap: "wrap" },
  filter: { flexGrow: 1, flexShrink: 1, flexBasis: 130, minWidth: 0, minHeight: 44, borderWidth: 1, borderColor: colors.neutralBorder, backgroundColor: colors.white, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 8, flexDirection: "row", alignItems: "center", gap: 6 },
  filterText: { flex: 1, fontSize: 13, color: colors.textDark, fontFamily: fonts.medium },
  summary: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: 6 },
  muted: { color: colors.textSecondary, fontSize: 12, fontFamily: fonts.regular },
  total: { color: colors.rmsColor, backgroundColor: colors.surfaceMintSoft, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 5, fontFamily: fonts.bold, fontSize: 13 },
  clear: { minHeight: 44, justifyContent: "center", paddingHorizontal: 8 },
  link: { color: colors.primaryBlue, fontFamily: fonts.bold, fontSize: 13 },
  card: { backgroundColor: colors.white, borderRadius: 14, borderCurve: "continuous", borderWidth: StyleSheet.hairlineWidth, borderColor: colors.neutralBorder, boxShadow: "0 2px 5px rgba(22, 48, 72, 0.09)" },
  cardSummary: { paddingHorizontal: 12, paddingVertical: 8, gap: 4, minHeight: 44 },
  compactFooter: { flexDirection: "row", alignItems: "center", gap: 6 },
  cardTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 6, flexWrap: "wrap" },
  title: { color: colors.textDark, fontFamily: fonts.bold, fontSize: 16 },
  badge: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6, backgroundColor: colors.surfaceBlue, alignSelf: "center" },
  badgeText: { color: colors.primaryBlue, fontFamily: fonts.bold, fontSize: 11 },
  nodes: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 7 },
  materialLabel: { flexDirection: "row", alignItems: "center", gap: 5 },
  materialDot: { width: 7, height: 7, borderRadius: 4 },
  node: { color: colors.textDark, fontFamily: fonts.medium, fontSize: 13 },
  metrics: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 8 },
  metric: { flex: 1, minWidth: 78, gap: 4 },
  value: { fontFamily: fonts.bold, fontSize: 14, color: colors.textDark, fontVariant: ["tabular-nums"] },
  laid: { color: colors.rmsColor, fontSize: 15 },
  laidMetric: { backgroundColor: colors.surfaceMintSoft, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4, flexShrink: 1 },
  unit: { fontSize: 12, fontFamily: fonts.medium },
  details: { borderTopWidth: 1, borderColor: colors.border, padding: 12, gap: 8 },
  detailText: { fontFamily: fonts.regular, fontSize: 13, color: colors.textDark, lineHeight: 19 },
  disclosure: { minHeight: 44, flexDirection: "row", alignItems: "center", gap: 8, borderTopWidth: StyleSheet.hairlineWidth, borderColor: colors.border, paddingTop: 8 },
  state: { padding: 24, alignItems: "center", gap: 12 },
  paginationFooter: { minHeight: 52, paddingVertical: 14, alignItems: "center", justifyContent: "center", gap: 8 },
  paginationRetry: { minHeight: 44, justifyContent: "center", paddingHorizontal: 12 },
  skeletonList: { gap: 10, paddingTop: 2 },
  skeletonCard: { minHeight: 116, overflow: "hidden", borderRadius: 14, borderWidth: StyleSheet.hairlineWidth, borderColor: colors.neutralBorder, backgroundColor: colors.white, padding: 12, gap: 10 },
  skeletonRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  skeletonBlock: { height: 12, overflow: "hidden", borderRadius: 6, backgroundColor: "#E8EEF4" },
  skeletonShine: { ...StyleSheet.absoluteFillObject, width: 180 },
  skeletonGradient: { flex: 1 },
  skeletonTitle: { width: "42%", height: 16 },
  skeletonDate: { width: "24%", height: 11 },
  skeletonLine: { width: "66%", height: 12 },
  skeletonShort: { width: "32%", height: 12 },
  skeletonMetric: { width: "24%", height: 18 },
  skeletonChip: { width: "28%", height: 20, borderRadius: 8 },
  stateTitle: { fontFamily: fonts.bold, fontSize: 16, color: colors.textDark, textAlign: "center" },
  stateText: { fontFamily: fonts.regular, fontSize: 14, color: colors.textSecondary, textAlign: "center" },
  error: { padding: 12, borderWidth: 1, borderColor: colors.danger, borderRadius: 10, gap: 8 },
  errorText: { color: colors.danger, fontFamily: fonts.regular, fontSize: 13 },
});
