import {
  PersonIcon,
  LockIcon,
  LoginIcon,
  AboutIcon,
  DashboardIcon,
  LogoutIcon,
  DownIcon,
  UpIcon,
  DirectionIcon,
  GoogleMapIcon,
  ZoneIcon,
  DistributorIcon,
  VillageIcon,
  TickIcon,
  GalleryIcon,
  UploadfileIcon,
  DeleteIcon,
  SupportIcon,
  LocationIcon,
} from "../assets/icons";

export const Icons = {
  person: PersonIcon,
  lock: LockIcon,
  login: LoginIcon,
  about: AboutIcon,
  dashboard: DashboardIcon,
  logout: LogoutIcon,
  down: DownIcon,
  up: UpIcon,
  direction:DirectionIcon,
  googleIcon: GoogleMapIcon,
  zone: ZoneIcon,
  distributor: DistributorIcon,
  village: VillageIcon,
  tickGreen: TickIcon,
  gallery: GalleryIcon,
  uploadfile: UploadfileIcon,
  delete: DeleteIcon,
  support: SupportIcon,
  location: LocationIcon
};
