export const createUnit = (data) => ({
  id: data.id,
  unitNo: data.unitNo,
  zone: data.zone,
  distributor: data.distributor,
  village: data.village,
  latitude: data.latitude,
  longitude: data.longitude,
  inlet: data.inlet,
  outlet: data.outlet,
  mechanical: data.mechanical,
  controller: data.controller,
  flushing: data.flushing,
  dry: data.dry,
  wet: data.wet,
  locationUpdatedAt: data.locationUpdatedAt,
  mechanicalRectification: data.mechanicalRectification,
  controllerRectification: data.controllerRectification,
  theftDamageReinstallation: data.theftDamageReinstallation,
  area: data.area,
  chakArea: data.chakArea,
});
